package ubi

// Operator describes Ubisoft metadata for a Rainbow Six Siege operator.
type Operator struct {
	Name       string
	Slug       string
	IsAttacker bool
}

// GetOperatorMap returns the supported operator metadata used by project tests and
// generation utilities. The keys intentionally use lowercase operator names so the
// map can be compared directly against the generated constants in disect/header.go.
func GetOperatorMap() (map[string]Operator, error) {
	operators := map[string]Operator{
		"ace":         {Name: "Ace", Slug: "ace", IsAttacker: true},
		"alibi":       {Name: "Alibi", Slug: "alibi", IsAttacker: false},
		"amaru":       {Name: "Amaru", Slug: "amaru", IsAttacker: true},
		"aruni":       {Name: "Aruni", Slug: "aruni", IsAttacker: false},
		"ash":         {Name: "Ash", Slug: "ash", IsAttacker: true},
		"azami":       {Name: "Azami", Slug: "azami", IsAttacker: false},
		"bandit":      {Name: "Bandit", Slug: "bandit", IsAttacker: false},
		"blackbeard":  {Name: "Blackbeard", Slug: "blackbeard", IsAttacker: true},
		"blitz":       {Name: "Blitz", Slug: "blitz", IsAttacker: true},
		"brava":       {Name: "Brava", Slug: "brava", IsAttacker: true},
		"buck":        {Name: "Buck", Slug: "buck", IsAttacker: true},
		"capitao":     {Name: "Capitao", Slug: "capitao", IsAttacker: true},
		"castle":      {Name: "Castle", Slug: "castle", IsAttacker: false},
		"caveira":     {Name: "Caveira", Slug: "caveira", IsAttacker: false},
		"clash":       {Name: "Clash", Slug: "clash", IsAttacker: false},
		"deimos":      {Name: "Deimos", Slug: "deimos", IsAttacker: true},
		"denari":      {Name: "Denari", Slug: "denari", IsAttacker: false},
		"dokkaebi":    {Name: "Dokkaebi", Slug: "dokkaebi", IsAttacker: true},
		"doc":         {Name: "Doc", Slug: "doc", IsAttacker: false},
		"echo":        {Name: "Echo", Slug: "echo", IsAttacker: false},
		"ela":         {Name: "Ela", Slug: "ela", IsAttacker: false},
		"fenrir":      {Name: "Fenrir", Slug: "fenrir", IsAttacker: false},
		"finka":       {Name: "Finka", Slug: "finka", IsAttacker: true},
		"flores":      {Name: "Flores", Slug: "flores", IsAttacker: true},
		"frost":       {Name: "Frost", Slug: "frost", IsAttacker: false},
		"fuze":        {Name: "Fuze", Slug: "fuze", IsAttacker: true},
		"glaz":        {Name: "Glaz", Slug: "glaz", IsAttacker: true},
		"goyo":        {Name: "Goyo", Slug: "goyo", IsAttacker: false},
		"gridlock":    {Name: "Gridlock", Slug: "gridlock", IsAttacker: true},
		"grim":        {Name: "Grim", Slug: "grim", IsAttacker: true},
		"hibana":      {Name: "Hibana", Slug: "hibana", IsAttacker: true},
		"iana":        {Name: "Iana", Slug: "iana", IsAttacker: true},
		"iq":          {Name: "IQ", Slug: "iq", IsAttacker: true},
		"jackal":      {Name: "Jackal", Slug: "jackal", IsAttacker: true},
		"jager":       {Name: "Jager", Slug: "jager", IsAttacker: false},
		"kaid":        {Name: "Kaid", Slug: "kaid", IsAttacker: false},
		"kali":        {Name: "Kali", Slug: "kali", IsAttacker: true},
		"kapkan":      {Name: "Kapkan", Slug: "kapkan", IsAttacker: false},
		"lesion":      {Name: "Lesion", Slug: "lesion", IsAttacker: false},
		"lion":        {Name: "Lion", Slug: "lion", IsAttacker: true},
		"maestro":     {Name: "Maestro", Slug: "maestro", IsAttacker: false},
		"maverick":    {Name: "Maverick", Slug: "maverick", IsAttacker: true},
		"melusi":      {Name: "Melusi", Slug: "melusi", IsAttacker: false},
		"mira":        {Name: "Mira", Slug: "mira", IsAttacker: false},
		"montagne":    {Name: "Montagne", Slug: "montagne", IsAttacker: true},
		"mozzie":      {Name: "Mozzie", Slug: "mozzie", IsAttacker: false},
		"mute":        {Name: "Mute", Slug: "mute", IsAttacker: false},
		"nokk":        {Name: "Nokk", Slug: "nokk", IsAttacker: true},
		"noor":        {Name: "Noor", Slug: "noor", IsAttacker: false},
		"nomad":       {Name: "Nomad", Slug: "nomad", IsAttacker: true},
		"osa":         {Name: "Osa", Slug: "osa", IsAttacker: true},
		"oryx":        {Name: "Oryx", Slug: "oryx", IsAttacker: false},
		"pulse":       {Name: "Pulse", Slug: "pulse", IsAttacker: false},
		"ram":         {Name: "Ram", Slug: "ram", IsAttacker: true},
		"rauora":      {Name: "Rauora", Slug: "rauora", IsAttacker: true},
		"rook":        {Name: "Rook", Slug: "rook", IsAttacker: false},
		"sentry":      {Name: "Sentry", Slug: "sentry", IsAttacker: false},
		"sens":        {Name: "Sens", Slug: "sens", IsAttacker: true},
		"skopos":      {Name: "Skopos", Slug: "skopos", IsAttacker: false},
		"sledge":      {Name: "Sledge", Slug: "sledge", IsAttacker: true},
		"smoke":       {Name: "Smoke", Slug: "smoke", IsAttacker: false},
		"solis":       {Name: "Solis", Slug: "solis", IsAttacker: false},
		"solidsnake":  {Name: "Solid Snake", Slug: "solidsnake", IsAttacker: true},
		"striker":     {Name: "Striker", Slug: "striker", IsAttacker: true},
		"tachanka":    {Name: "Tachanka", Slug: "tachanka", IsAttacker: false},
		"thermite":    {Name: "Thermite", Slug: "thermite", IsAttacker: true},
		"thorn":       {Name: "Thorn", Slug: "thorn", IsAttacker: false},
		"thunderbird": {Name: "Thunderbird", Slug: "thunderbird", IsAttacker: false},
		"thatcher":    {Name: "Thatcher", Slug: "thatcher", IsAttacker: true},
		"tubarao":     {Name: "Tubarao", Slug: "tubarao", IsAttacker: false},
		"twitch":      {Name: "Twitch", Slug: "twitch", IsAttacker: true},
		"valkyrie":    {Name: "Valkyrie", Slug: "valkyrie", IsAttacker: false},
		"vigil":       {Name: "Vigil", Slug: "vigil", IsAttacker: false},
		"warden":      {Name: "Warden", Slug: "warden", IsAttacker: false},
		"wamai":       {Name: "Wamai", Slug: "wamai", IsAttacker: false},
		"ying":        {Name: "Ying", Slug: "ying", IsAttacker: true},
		"zero":        {Name: "Zero", Slug: "zero", IsAttacker: true},
		"zofia":       {Name: "Zofia", Slug: "zofia", IsAttacker: true},
	}

	return operators, nil
}
